#!/bin/bash
# sudo vim /etc/update-motd.d/10-help-text

color1='\033[1;31m'    # light red
color2='\033[1;35m'    # light purple
color3='\033[0;33m'    # light yellow
nocolor='\033[0m'      # no color
companyname='\033[1;34mWipfVaio\033[0m'
divisionname='\033[1;32mWipf Server by Tobias Fritsch\033[0m'

printf "               ${color1}.-.${nocolor}\n"
printf "         ${color2}.-'\`\`${color1}(   )    ${companyname}${nocolor}\n"
printf "      ${color3},\`\\ ${color2}\\    ${color1}\`-\`${color2}.    ${divisionname}${nocolor}\n"
printf "     ${color3}/   \\ ${color2}'\`\`-.   \`   ${color3}`lsb_release -s -d`${nocolor}\n"
printf "   ${color2}.-.  ${color3},       ${color2}\`___:  ${nocolor}`uname -srmo`${nocolor}\n"
printf "  ${color2}(   ) ${color3}:       ${color1} ___   ${nocolor}`date +"%A, %e %B %Y, %R"`${nocolor}\n"
printf "   ${color2}\`-\`  ${color3}\`      ${color1} ,   :${nocolor} ${nocolor}\n"
printf "     ${color3}\\   / ${color1},..-\`   ,${nocolor}   Lan IP: `/sbin/ifconfig enp4s0 | /bin/grep "inet addr" | /usr/bin/cut -d ":" -f 2 | /usr/bin/cut -d " " -f 1`\n"
printf "      ${color3}\`./${color1} /    ${color3}.-.${color1}\`${nocolor}    Wlan IP: `/sbin/ifconfig wlp2s0 | /bin/grep "inet addr" | /usr/bin/cut -d ":" -f 2 | /usr/bin/cut -d " " -f 1`\n"
printf "         ${color1}\`-..-${color3}(   )${nocolor}    External IP: `/usr/bin/wget -q -O - http://icanhazip.com/ | /usr/bin/tail`\n"
printf "               ${color3}\`-\`${nocolor}     Uptime: `/usr/bin/uptime -p`\n"
printf "                      ${color1} `acpi`${nocolor}\n"
printf "\n${nocolor}`sensors | grep C`"
